<?xml version="1.0"?>
<package format="3">
  <name>robot_navigation</name>
  <version>0.1.0</version>
  <description>Configuration Nav2 du robot agricole v2.</description>
  <maintainer email="xav@localhost">Xavier Rossignol</maintainer>
  <license>Apache-2.0</license>

  <exec_depend>nav2_bringup</exec_depend>
  <exec_depend>nav2_msgs</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
